### ISSUE TITLE
Not saving new entries in Firefox?

### ISSUE THREAD

**Issue by bouncinglime** [pfn/passifox#584]
There seem to be a couple other issues around this, so I'm wondering if maybe the whole feature isn't working. There doesn't seem to be a way to add new entries via passifox, and it would be nice if there were.

Firefox version 50.1.0
passifox version 1.2.2
OS : Windows 8.1

Thanks.

**Comment by nerdazoid** [comment]
I came here looking for information on this because I couldn't figure out why my new entries weren't being saved. For a while I thought it just wasn't in the functionality of this extension, but then I look in my DB and I saw a single entry under the "KeyPassHttp Passwords" category, so I knew it had to have worked at least once.

I went through a bunch of websites trying to get it to trigger a save, creating new accounts and updating old ones. Then I noticed there is a "Save Credentials" option in the context menu, so I started trying that button when filling out a password field, and it seemed to do nothing. I was watching the console window for the extension looking for clues as to why it wasn't working and found nothing.

FINALLY, I randomly looked up at the extension toolbar right after I clicked "Save Credentials", and for a few seconds after I press the context menu option, the icon in the toolbar flashes red, and you then have to click that button to trigger the save. When I follow all of these steps it seems to work.

Now I think it used to automatically detect updates or at least new passwords, without having to touch the context menu. It must because I didn't know the context menu item existed, but I had an entry in the database. So maybe something caused the autodetect to stop working, and since it looks like the firefox version doesn't have the option in the context menu, or an icon in the toolbar, there is no way to manually trigger it?

Anyway, I just wanted to drop in with a bit more info, mainly that it does work on Chrome, you just have to manually trigger it.

**Comment by bouncinglime** [comment]
@nerdazoid Yes, it works very easily in Chrome. If you want the icon to blink for longer to give you more time to click on it, you can change that in the settings. Click the icon, click settings, and it's the first "blink time" option in General.

However, this is not an option in Firefox. There is no icon that is displayed. According to the passifox documentation, entries are added automatically... but this is not happening, and there's no manual work-around.

**Comment by pfn** [comment]
Both chrome and passifox should require manual "yes I want to save" -- on
firefox, this functionality is prompted by the browser itself and not
passifox.

**Comment by bouncinglime** [comment]
In Chrome, you can get an option to save by clicking the chromeIPass icon. In Firefox, there is no icon to click for PassIFox, and there is no browser-based prompt either.

**Comment by hausmaen** [comment]
I can confirm that the plugin does not work for my Firefox anymore. I get no more request about saving or updating my credentials on Keepass

**Comment by hausmaen** [comment]
I just found another issue-report which was solving the problem for me!

seems as my Firefox settings were causing the problem as a checkbox was not checked to store credentials at all. this way Firefox did not forwarded them to passifox.

check out: Einstellungen --> Sicherheit --> Zugangsdaten für Websites speichern
in English something like Settings --> Security --> Store credentials for website

https://github.com/pfn/passifox/issues/611

**Comment by bouncinglime** [comment]
@hausmaen Is that in the settings of Firefox, or Keepass? I don't want Firefox to remember passwords, so I am not going to enable that setting in Firefox. If that's the way that this extension needs to send passwords to Keepass, then I will leave it broken.

**Comment by hausmaen** [comment]
As far as I can see Firefox is not storing passwords as long as Keepass is running. But yes, the setting is on Firefox.

**Comment by bouncinglime** [comment]
@hausmaen Interesting. Thanks for the info!

**Comment by bouncinglime** [comment]
I've switched extensions and am now using [Kee](https://addons.mozilla.org/en-GB/firefox/addon/keefox/) instead. It works brilliantly!
