### ISSUE TITLE
Disable popup dialogue when specifying login location with multiple logins present.

### ISSUE THREAD

**Issue by NvrBst** [pfn/passifox#63]
Right-click on a Form in a Page > ChromeIPass > Fill User/Pass (Or Pass only)

If you have multiple logins, a dialog pops up with the title "ChromeIPass":
  More than one login was found in KeePass, press the ChromeIPass icon for more options

Then you can click "OK". This seems to be the only dialog which pop's up often in ChromeIPass. Pressing "OK" each time then going up to the ChromeIPass icon and chooseing the login seems unnessasary.

You should just display the information from the ChromeIPass "tooltip" like all other information is displayed. Or automatically open the ChromeIPass icon so the user can choose the login he wants in this situation would be more efficient.

Having dialogs pop up all the time gets annoying. Else if you can have an option to disable this popup that would be fine as well.

**Comment by shackrock** [comment]
I can say that when using the keyboard shortcut "control+shift+F6" to autofill the username and password, the pop up still comes up.  However, I must use this shortcut on many pages because otherwise there is no autofill dropdown to show up.  The only fix after this pops up is to click ok, go to the icon for ChromeIPass in Chrome, and then pick the login I want to use.  

Doesn't seem to be fixed in the latest version "2.6.8"
